### ISSUE TITLE
你好，能提供预训练模型测试一下吗

### ISSUE THREAD

**Issue by wodsoe** [ShawnNew/AMSMNet#19]
你好，能提供预训练模型测试一下吗？
另外，如果使用爱分割的数据集，https://github.com/aisegmentcn/matting_human_datasets，
该怎么处理呢

**Comment by ShawnNew** [comment]
You may consider using [this](https://github.com/ShawnNew/AMSMNet/blob/master/pretrained.pth) as the pretrained model.
I cannot open the link you provided; however, you can finetune the dataset using the pretrained-model.

**Comment by wodsoe** [comment]
OK.Thank you!
The url is 
https://github.com/aisegmentcn/matting_human_datasets

**Comment by ShawnNew** [comment]
You can write your customized data_loader and finetune the model.
Good luck.
